### ISSUE TITLE
GA360 is not longer detected in Omnibug 

### ISSUE THREAD

**Issue by clemenscito** [MisterPhilip/omnibug#230]
**Describe the bug**
Regardless of the settings regular GA360 / Universal GA events are no longer detectable in Omnibug. 

**To Reproduce**
1. Go to 'omnibug'
2. Click on '.any event on our page'
3. See that GA4 fires but not universal/G3
4. Please please fix

**Comment by Harrybdo** [comment]
Everyone on my team is also having the same issue. No GA universal debugging despite seeing the GA universal collect calls in the network traffic.

**Comment by MisterPhilip** [comment]
Should be fixed; I checked against both of y'all's URLs and Omnibug was matching to the network panel. It may take the extension stores a day or two to fully roll out. Thanks for the report and details and sorry for the inconvenience!

**Comment by clemenscito** [comment]
Fantastic, thank you so much for the quick fix!

**Comment by aioun92** [comment]
this still isn't fixed for me.  i'm on 1.21.1 and still not seeing ga ua calls.  anyone else still having trouble?

**Comment by aioun92** [comment]
> @aioun92 can you send me a URL to replicate the issue?

hey.  i'm so sorry. looks like clearing cache fixed this!  thanks for the quick reply!
